// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vdut.h for the primary calling header

#include "Vdut__pch.h"
#include "Vdut_ConvCore__Ia_IBe.h"

VL_ATTR_COLD void Vdut_ConvCore__Ia_IBe___ctor_var_reset(Vdut_ConvCore__Ia_IBe* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vdut__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vdut_ConvCore__Ia_IBe___ctor_var_reset\n"); );
    // Body
    for (int __Vi0 = 0; __Vi0 < 10; ++__Vi0) {
        VL_RAND_RESET_W(196, vlSelf->img_in[__Vi0]);
    }
    VL_RAND_RESET_W(90, vlSelf->weights);
    VL_RAND_RESET_W(144, vlSelf->img_out);
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__0__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__1__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__2__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__3__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__4__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__5__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__6__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__7__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__8__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__9__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__10__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__0__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__0__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__0__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__1__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__1__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__1__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__2__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__2__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__2__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__3__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__3__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__3__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__4__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__4__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__4__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__5__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__5__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__5__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__6__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__6__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__6__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__7__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__7__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__7__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__8__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__8__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__8__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__9__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__9__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__9__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__10__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__10__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__10__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
    VL_RAND_RESET_W(90, vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__11__KET____DOT__patch);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__11__KET____DOT__popcount = VL_RAND_RESET_I(8);
    vlSelf->__PVT__out_row_gen__BRA__11__KET____DOT__out_col_gen__BRA__11__KET____DOT__adder_block__DOT__unnamedblk1__DOT__i = 0;
}
